// <auto-generated />
using System;
using LanguagueLearningApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LanguagueLearningApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.BaiHoc", b =>
                {
                    b.Property<int>("MaBaiHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiHoc"));

                    b.Property<int?>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBaiHoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaBaiHoc");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("BaiHocs");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.BaiNop", b =>
                {
                    b.Property<int>("MaBaiNop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiNop"));

                    b.Property<string>("BaiLam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Diem")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("LinkAmThanh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaBaiTap")
                        .HasColumnType("int");

                    b.Property<int?>("MaHocSinh")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Chờ chấm");

                    b.HasKey("MaBaiNop");

                    b.HasIndex("MaBaiTap");

                    b.HasIndex("MaHocSinh");

                    b.ToTable("BaiNops");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.BaiTap", b =>
                {
                    b.Property<int>("MaBaiTap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiTap"));

                    b.Property<string>("CauHoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiemToiDa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<string>("Loai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaBaiHoc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaBaiTap");

                    b.HasIndex("MaBaiHoc");

                    b.ToTable("BaiTaps");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.BangXepHang", b =>
                {
                    b.Property<int>("MaBXH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBXH"));

                    b.Property<int?>("Hang")
                        .HasColumnType("int");

                    b.Property<string>("KyHan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaHocSinh")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TongDiem")
                        .HasColumnType("int");

                    b.HasKey("MaBXH");

                    b.HasIndex("MaHocSinh");

                    b.ToTable("BangXepHangs");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.BaoCaoZalo", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCao"));

                    b.Property<string>("Loi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaHocSinh")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhuHuynh")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Chờ gửi");

                    b.HasKey("MaBaoCao");

                    b.HasIndex("MaHocSinh");

                    b.HasIndex("MaPhuHuynh");

                    b.ToTable("BaoCaoZalos");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.CauHoiTracNghiem", b =>
                {
                    b.Property<int>("MaCauHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCauHoi"));

                    b.Property<string>("DapAn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Diem")
                        .HasColumnType("int");

                    b.Property<string>("LuaChon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaBaiTap")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungCauHoi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCauHoi");

                    b.HasIndex("MaBaiTap");

                    b.ToTable("CauHoiTracNghiems");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.ChatBot_HocSinh", b =>
                {
                    b.Property<int>("MaTinChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinChat"));

                    b.Property<string>("ChuDe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("DoChinhXac")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("MaHocSinh")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungNguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanHoiAI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("YDinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTinChat");

                    b.HasIndex("MaHocSinh");

                    b.ToTable("ChatBot_HocSinhs");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.ChuDeChatBot", b =>
                {
                    b.Property<int>("MaChuDe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuDe"));

                    b.Property<bool?>("KichHoat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenChuDe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaChuDe");

                    b.ToTable("ChuDeChatBots");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.GiaoVien", b =>
                {
                    b.Property<int>("MaGiaoVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaoVien"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Truong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaGiaoVien");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.ToTable("GiaoViens");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.HocSinh", b =>
                {
                    b.Property<int>("MaHocSinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocSinh"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lop")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaPhuHuynh")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TongDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Truong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaHocSinh");

                    b.HasIndex("MaPhuHuynh");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.ToTable("HocSinhs");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.HocSinh_PhanThuong", b =>
                {
                    b.Property<int>("MaHocSinh")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaPhanThuong")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.HasKey("MaHocSinh", "MaPhanThuong");

                    b.HasIndex("MaPhanThuong");

                    b.ToTable("HocSinh_PhanThuongs");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.KhoaHoc", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<string>("CapDo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaGiaoVien")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhoaHoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaKhoaHoc");

                    b.HasIndex("MaGiaoVien");

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.LoiNguPhap", b =>
                {
                    b.Property<int>("MaLoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoi"));

                    b.Property<string>("DoanLoi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GoiYSua")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiLoi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaBaiNop")
                        .HasColumnType("int");

                    b.Property<int?>("ViTriBatDau")
                        .HasColumnType("int");

                    b.Property<int?>("ViTriKetThuc")
                        .HasColumnType("int");

                    b.HasKey("MaLoi");

                    b.HasIndex("MaBaiNop");

                    b.ToTable("LoiNguPhaps");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.NhatKyAI", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("HanhDong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KetQua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaHocSinh")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Thành công");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaHocSinh");

                    b.ToTable("NhatKyAIs");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.NhiemVu", b =>
                {
                    b.Property<int>("MaNhiemVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhiemVu"));

                    b.Property<string>("ChuKy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("DangHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("DiemThuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenNhiemVu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaNhiemVu");

                    b.ToTable("NhiemVus");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.NhiemVuHocSinh", b =>
                {
                    b.Property<int>("MaHocSinh")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("MaNhiemVu")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime?>("NgayGiao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đang giao");

                    b.HasKey("MaHocSinh", "MaNhiemVu");

                    b.HasIndex("MaNhiemVu");

                    b.ToTable("NhiemVuHocSinhs");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.PhanHoi", b =>
                {
                    b.Property<int>("MaPhanHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanHoi"));

                    b.Property<int?>("MaBaiNop")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXetGV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanHoiAI")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhanHoi");

                    b.HasIndex("MaBaiNop")
                        .IsUnique()
                        .HasFilter("[MaBaiNop] IS NOT NULL");

                    b.ToTable("PhanHois");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.PhanThuong", b =>
                {
                    b.Property<int>("MaPhanThuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanThuong"));

                    b.Property<int?>("DiemCan")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenPhanThuong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaPhanThuong");

                    b.ToTable("PhanThuongs");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.PhanTichAI", b =>
                {
                    b.Property<int>("MaPhanTich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanTich"));

                    b.Property<string>("ChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DoChinhXacNguPhap")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("DoChinhXacPhatAm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("DoDaDangTuVung")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("DoLuuLoat")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("MaBaiNop")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayPhanTich")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXetAI")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhanTich");

                    b.HasIndex("MaBaiNop")
                        .IsUnique()
                        .HasFilter("[MaBaiNop] IS NOT NULL");

                    b.ToTable("PhanTichAIs");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.PhuHuynh", b =>
                {
                    b.Property<int>("MaPhuHuynh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuHuynh"));

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ZaloID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhuHuynh");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.ToTable("PhuHuynhs");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.TienDo", b =>
                {
                    b.Property<int>("MaTienDo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTienDo"));

                    b.Property<DateTime?>("LanCuoiHoatDong")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaBaiHoc")
                        .HasColumnType("int");

                    b.Property<int?>("MaHocSinh")
                        .HasColumnType("int");

                    b.Property<decimal?>("TiLeHoanThanh")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("MaTienDo");

                    b.HasIndex("MaBaiHoc");

                    b.HasIndex("MaHocSinh");

                    b.ToTable("TienDos");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.TinNhan", b =>
                {
                    b.Property<int>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinNhan"));

                    b.Property<int?>("MaNguoiGui")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiNhan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTinNhan");

                    b.HasIndex("MaNguoiGui");

                    b.HasIndex("MaNguoiNhan");

                    b.ToTable("TinNhans");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.BaiHoc", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("BaiHocs")
                        .HasForeignKey("MaKhoaHoc");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.BaiNop", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.BaiTap", "BaiTap")
                        .WithMany("BaiNops")
                        .HasForeignKey("MaBaiTap");

                    b.HasOne("LanguagueLearningApp.Api.Models.HocSinh", "HocSinh")
                        .WithMany("BaiNops")
                        .HasForeignKey("MaHocSinh");

                    b.Navigation("BaiTap");

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.BaiTap", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.BaiHoc", "BaiHoc")
                        .WithMany("BaiTaps")
                        .HasForeignKey("MaBaiHoc");

                    b.Navigation("BaiHoc");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.BangXepHang", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.HocSinh", "HocSinh")
                        .WithMany("BangXepHangs")
                        .HasForeignKey("MaHocSinh");

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.BaoCaoZalo", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.HocSinh", "HocSinh")
                        .WithMany("BaoCaoZalos")
                        .HasForeignKey("MaHocSinh");

                    b.HasOne("LanguagueLearningApp.Api.Models.PhuHuynh", "PhuHuynh")
                        .WithMany("BaoCaoZalos")
                        .HasForeignKey("MaPhuHuynh");

                    b.Navigation("HocSinh");

                    b.Navigation("PhuHuynh");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.CauHoiTracNghiem", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.BaiTap", "BaiTap")
                        .WithMany("CauHoiTracNghiems")
                        .HasForeignKey("MaBaiTap");

                    b.Navigation("BaiTap");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.ChatBot_HocSinh", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.HocSinh", "HocSinh")
                        .WithMany("ChatBot_HocSinhs")
                        .HasForeignKey("MaHocSinh");

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.GiaoVien", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("GiaoVien")
                        .HasForeignKey("LanguagueLearningApp.Api.Models.GiaoVien", "MaTaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.HocSinh", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.PhuHuynh", "PhuHuynh")
                        .WithMany("HocSinhs")
                        .HasForeignKey("MaPhuHuynh");

                    b.HasOne("LanguagueLearningApp.Api.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("HocSinh")
                        .HasForeignKey("LanguagueLearningApp.Api.Models.HocSinh", "MaTaiKhoan");

                    b.Navigation("PhuHuynh");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.HocSinh_PhanThuong", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.HocSinh", "HocSinh")
                        .WithMany("HocSinh_PhanThuongs")
                        .HasForeignKey("MaHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguagueLearningApp.Api.Models.PhanThuong", "PhanThuong")
                        .WithMany("HocSinh_PhanThuongs")
                        .HasForeignKey("MaPhanThuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("PhanThuong");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.KhoaHoc", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.GiaoVien", "GiaoVien")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("MaGiaoVien");

                    b.Navigation("GiaoVien");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.LoiNguPhap", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.BaiNop", "BaiNop")
                        .WithMany("LoiNguPhaps")
                        .HasForeignKey("MaBaiNop");

                    b.Navigation("BaiNop");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.NhatKyAI", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.HocSinh", "HocSinh")
                        .WithMany("NhatKyAIs")
                        .HasForeignKey("MaHocSinh");

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.NhiemVuHocSinh", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.HocSinh", "HocSinh")
                        .WithMany("NhiemVuHocSinhs")
                        .HasForeignKey("MaHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguagueLearningApp.Api.Models.NhiemVu", "NhiemVu")
                        .WithMany("NhiemVuHocSinhs")
                        .HasForeignKey("MaNhiemVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("NhiemVu");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.PhanHoi", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.BaiNop", "BaiNop")
                        .WithOne("PhanHoi")
                        .HasForeignKey("LanguagueLearningApp.Api.Models.PhanHoi", "MaBaiNop");

                    b.Navigation("BaiNop");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.PhanTichAI", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.BaiNop", "BaiNop")
                        .WithOne("PhanTichAI")
                        .HasForeignKey("LanguagueLearningApp.Api.Models.PhanTichAI", "MaBaiNop");

                    b.Navigation("BaiNop");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.PhuHuynh", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("PhuHuynh")
                        .HasForeignKey("LanguagueLearningApp.Api.Models.PhuHuynh", "MaTaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.TienDo", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.BaiHoc", "BaiHoc")
                        .WithMany("TienDos")
                        .HasForeignKey("MaBaiHoc");

                    b.HasOne("LanguagueLearningApp.Api.Models.HocSinh", "HocSinh")
                        .WithMany("TienDos")
                        .HasForeignKey("MaHocSinh");

                    b.Navigation("BaiHoc");

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.TinNhan", b =>
                {
                    b.HasOne("LanguagueLearningApp.Api.Models.TaiKhoan", "NguoiGui")
                        .WithMany("TinNhanGui")
                        .HasForeignKey("MaNguoiGui")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LanguagueLearningApp.Api.Models.TaiKhoan", "NguoiNhan")
                        .WithMany("TinNhanNhan")
                        .HasForeignKey("MaNguoiNhan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.BaiHoc", b =>
                {
                    b.Navigation("BaiTaps");

                    b.Navigation("TienDos");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.BaiNop", b =>
                {
                    b.Navigation("LoiNguPhaps");

                    b.Navigation("PhanHoi");

                    b.Navigation("PhanTichAI");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.BaiTap", b =>
                {
                    b.Navigation("BaiNops");

                    b.Navigation("CauHoiTracNghiems");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.GiaoVien", b =>
                {
                    b.Navigation("KhoaHocs");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.HocSinh", b =>
                {
                    b.Navigation("BaiNops");

                    b.Navigation("BangXepHangs");

                    b.Navigation("BaoCaoZalos");

                    b.Navigation("ChatBot_HocSinhs");

                    b.Navigation("HocSinh_PhanThuongs");

                    b.Navigation("NhatKyAIs");

                    b.Navigation("NhiemVuHocSinhs");

                    b.Navigation("TienDos");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.KhoaHoc", b =>
                {
                    b.Navigation("BaiHocs");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.NhiemVu", b =>
                {
                    b.Navigation("NhiemVuHocSinhs");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.PhanThuong", b =>
                {
                    b.Navigation("HocSinh_PhanThuongs");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.PhuHuynh", b =>
                {
                    b.Navigation("BaoCaoZalos");

                    b.Navigation("HocSinhs");
                });

            modelBuilder.Entity("LanguagueLearningApp.Api.Models.TaiKhoan", b =>
                {
                    b.Navigation("GiaoVien");

                    b.Navigation("HocSinh");

                    b.Navigation("PhuHuynh");

                    b.Navigation("TinNhanGui");

                    b.Navigation("TinNhanNhan");
                });
#pragma warning restore 612, 618
        }
    }
}
